[package]
name = "std"
version = "0.0.0"
authors = ["Baidu"]
build = "build.rs"

[features]
default = []
global_exit = []
backtrace = ["stdio"]
stdio = []

[build-dependencies]
build_helper = { path = "../build_helper" }
gcc = "0.3.54"

[dependencies]
sgx_types = { path = "../sgx_types" }
sgx_trts = { path = "../sgx_trts" }
sgx_alloc = { path = "../sgx_alloc" }
sgx_tprotected_fs = { path = "../sgx_tprotected_fs" }
